### PR TITLE
Weather-forecast

### PR DESCRIPTION
**Pull request by AkintoyeOlamide**
This is a weather app that lets you check the current weather of any place. It was built with Javascript webpack, HTML, and CSS. API from openweather.

### CODE REVIEW

**Review by NtwaliHeritier — COMMENTED** [review]
### **STATUS: INVALIDATED❌❌❌❌❌❌**

Hello @AkintoyeOlamide 
This is a great project. However I have to invalidate it because linters are not triggered.
Kindly add it and ask for another review👍👍.

Happy coding💻💻💻💻💻

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Invalid PR 😞 😞 😞 
Am marking this PR as invalid because you lack a meaningful description. The description helps TSE to look at what you have done at a glance and it's a requirement.
Please add that and send it for another review.


### Martin Afani
#### Slack: whiz25

**Review by trekab — COMMENTED** [review]
#### Invalid! :stop_sign: 
Hi @AkintoyeOlamide! Unfortunately, I have to invalidate your code review request because __you did not follow [Git Flow](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59882084/)__ as expected. I have noticed that this is the third invalidation you're getting. I'd like to point out some points to help you overcome this in your next submission.
Try to create a checklist for your code review requests based on the following links:

- [Professional GitHub repository](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
- [GitHub Flow](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/)
- [Git Flow](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59882084/)
- [linter errors as a reason of project invalidation](https://microverse.zendesk.com/hc/en-us/articles/1500002085202-February-2nd-2021-linter-errors-as-a-reason-of-project-invalidation-)

__Please make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__[Treasure Kabareebe](https://trekab.github.io)__

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Invalid PR 😞 😞 😞 
Am marking this PR as invalid because you still don't follow the correct Git flow as suggested. Make the PR from `feature-branch` to `development-branch`.

### Martin Afani
#### Slack: whiz25

**Comment by whiz25** [comment]
## Invalid PR
Fix the change suggested before submitting this PR.

**Pull request closed without merging**
